# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('first', models.CharField(max_length=30, verbose_name='一级分类')),
                ('second', models.CharField(blank=True, max_length=30, verbose_name='二级分类')),
                ('third', models.CharField(blank=True, max_length=30, verbose_name='三级分类')),
                ('forth', models.CharField(blank=True, max_length=30, verbose_name='四级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-catid'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('hisid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('grade', models.CharField(max_length=30, verbose_name='分数')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.Catagory', verbose_name='用户')),
            ],
            options={
                'verbose_name': '历史',
                'verbose_name_plural': '历史',
                'ordering': ['-hisid'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('sex', models.CharField(max_length=30, verbose_name='性别')),
                ('school', models.CharField(max_length=30, verbose_name='学校')),
                ('grade', models.CharField(max_length=30, verbose_name='年级')),
                ('qq', models.CharField(max_length=30, verbose_name='QQ号')),
                ('wechat', models.CharField(max_length=30, verbose_name='微信标识')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-userid'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('wordid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('word', models.CharField(max_length=30, verbose_name='单词')),
                ('mean_en', models.CharField(max_length=100, verbose_name='英文解释')),
                ('mean_zh', models.CharField(max_length=100, verbose_name='中文释义')),
                ('catagory', models.ManyToManyField(to='english.Catagory', verbose_name='标签')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'ordering': ['-wordid'],
            },
        ),
        migrations.CreateModel(
            name='Wrong',
            fields=[
                ('wrongid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.User', verbose_name='用户')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.Word', verbose_name='用户')),
            ],
            options={
                'verbose_name': '错误记录',
                'verbose_name_plural': '错误记录',
                'ordering': ['-wrongid'],
            },
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.User', verbose_name='用户'),
        ),
    ]
