# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrong',
            name='times',
            field=models.IntegerField(default=1, verbose_name='次数'),
        ),
        migrations.AlterField(
            model_name='history',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.Catagory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='history',
            name='grade',
            field=models.CharField(max_length=200, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='wrong',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.Word', verbose_name='单词'),
        ),
    ]
